// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOwvf_6jQu8D3Gx6DE5Gt9RPU2SQGrNqs',
    appId: '1:608042484719:web:772982d182b535d950ac1a',
    messagingSenderId: '608042484719',
    projectId: 'elderlycareapp-553a8',
    authDomain: 'elderlycareapp-553a8.firebaseapp.com',
    storageBucket: 'elderlycareapp-553a8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkthA2VzHbwAwwvlwP8X9hyk8jlEDXMEU',
    appId: '1:608042484719:android:330e2067d058cb0e50ac1a',
    messagingSenderId: '608042484719',
    projectId: 'elderlycareapp-553a8',
    storageBucket: 'elderlycareapp-553a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOLXYwg3LgO8lcIQqgZn87atbFB2v7eDg',
    appId: '1:608042484719:ios:a03ef2227175e75650ac1a',
    messagingSenderId: '608042484719',
    projectId: 'elderlycareapp-553a8',
    storageBucket: 'elderlycareapp-553a8.firebasestorage.app',
    iosBundleId: 'com.example.elderlycareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOLXYwg3LgO8lcIQqgZn87atbFB2v7eDg',
    appId: '1:608042484719:ios:a03ef2227175e75650ac1a',
    messagingSenderId: '608042484719',
    projectId: 'elderlycareapp-553a8',
    storageBucket: 'elderlycareapp-553a8.firebasestorage.app',
    iosBundleId: 'com.example.elderlycareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOwvf_6jQu8D3Gx6DE5Gt9RPU2SQGrNqs',
    appId: '1:608042484719:web:be214d65ca5e8e4350ac1a',
    messagingSenderId: '608042484719',
    projectId: 'elderlycareapp-553a8',
    authDomain: 'elderlycareapp-553a8.firebaseapp.com',
    storageBucket: 'elderlycareapp-553a8.firebasestorage.app',
  );
}
